---
- name: PLAY - Build the Lab
  hosts: cisco_cat9kv
  gather_facts: no
  vars_files:
    - ./datamodel.yml

  tasks:

    - name: Enable IP Routing
      cisco.ios.ios_config:
        lines:
          - ip routing

    - name: Configure Ethernet Interfaces - L3 Mode
      cisco.ios.ios_interfaces:
        config:
          - name: "{{ item.key }}"
            mode: layer3
        state: merged
      when: "'Ethernet' in item.key"
      loop: "{{ dm.underlay.interfaces[inventory_hostname] | dict2items }}"

    - name: Configure IP Addressing
      cisco.ios.ios_l3_interfaces:
        config:
          - name: "{{ item.key }}"
            ipv4:
              - address: "{{item.value}}"
        state: merged
      loop: "{{ dm.underlay.interfaces[inventory_hostname] | dict2items }}"

    - name: Create OSPF Process
      cisco.ios.ios_ospfv2:
        config:
          processes:
            - process_id: 1
              router_id: "{{ dm.underlay.interfaces[inventory_hostname].Loopback0.split('/')[0] }}"

    - name: Configure OSPF - Loopback Interfaces
      cisco.ios.ios_ospf_interfaces:
        config:
          - name: "{{ item.key }}"
            address_family:
              - afi: ipv4
                process:
                  id: 1
                  area_id: 0
        state: merged
      when: "'Loopback' in item.key"
      loop: "{{ dm.underlay.interfaces[inventory_hostname] | dict2items }}"

    - name: Configure OSPF - Ethernet Interfaces
      cisco.ios.ios_ospf_interfaces:
        config:
          - name: "{{ item.key }}"
            address_family:
              - afi: ipv4
                process:
                  id: 1
                  area_id: 0
                network:
                  point_to_point: true
        state: merged
      when: "'Ethernet' in item.key"
      loop: "{{ dm.underlay.interfaces[inventory_hostname] | dict2items }}"

    - name: Enable Multicast Routing and Configure RP
      vars:
        rp_address: "{{ dm.underlay.interfaces['s1'].Loopback255.split('/')[0] }}"
      cisco.ios.ios_config:
        lines:
          - ip multicast-routing
          - "ip pim rp-address {{ rp_address }}"

    - name: Enable PIM
      vars:
        rp_address: "{{ dm.underlay.interfaces['s1'].Loopback255.split('/')[0] }}"
      cisco.ios.ios_config:
        lines:
          - ip pim sparse-mode
        parents: "interface {{ item.key }}"
      loop: "{{ dm.underlay.interfaces[inventory_hostname] | dict2items }}"

    - name: Configure MSDP for Anycast RP
      vars:
        msdp_peer: "{{ 
            dm.underlay.interfaces['s1'].Loopback0.split('/')[0] 
            if inventory_hostname == 's2'
            else dm.underlay.interfaces['s2'].Loopback0.split('/')[0] }}"
      cisco.ios.ios_config:
        lines:
          - "ip msdp peer {{ msdp_peer }} connect-source Loopback0 remote-as {{ dm.evpn.asn }}"
      when: inventory_hostname in dm.evpn.spines

    - name: Deploy BGP EVPN Configuration
      cisco.ios.ios_config:
        src: bgp.j2

    - name: Deploy EVPN Configurations
      cisco.ios.ios_config:
        src: evpn.j2
      when: inventory_hostname in dm.evpn.leaves

    - name: Configure Access Ports
      cisco.ios.ios_config:
        src: access-ports.j2
      when: inventory_hostname in dm.evpn.leaves

    - name: Save device configurations
      cisco.ios.ios_config:
        save_when: modified
